name-template: '$RESOLVED_VERSION'
tag-template: '$RESOLVED_VERSION'
categories:
  - title: '🤖 Android'
    label: 'android'
  - title: '🍎 Apple'
    label: 'apple'
  - title: '🌐 JavaScript'
    label: 'javascript'
  - title: '🖥️ JVM'
    label: 'jvm'

  - title: '🧰 Maintenance'
    labels:
      - 'maintenance'
      - 'renovate'
change-template: '- $TITLE (#$NUMBER)'
exclude-labels:
  - 'skip-changelog'
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
template: $CHANGES
