categories:
  - title: 'Android'
    label: 'android'
  - title: 'Apple'
    label: 'apple'
  - title: 'JavaScript'
    label: 'javascript'
  - title: '🧰 Maintenance'
    labels:
      - 'maintenance'
      - 'renovate'
change-template: '- $TITLE (#$NUMBER)'
exclude-labels:
  - 'skip-changelog'
template: |
  ## 🚀 Changes
  
  $CHANGES
