// Bluetooth SIG assigned numbers sourced from:
// - https://bitbucket.org/bluetooth-SIG/public/src/main/assigned_numbers/uuids/
// - Originally generated by https://github.com/chungchungdev/kotlin-bluetoothsig-assigned-numbers
//   Copyright chungchungdev, used under the Apache License, Version 2.0.
//
// https://www.bluetooth.com/specifications/assigned-numbers/
//
// Last update: 2026-07-18 (UTC+0)

@file:Suppress("ktlint:standard:class-naming")

package org.bluetooth

/**
 * Bluetooth SIG assigned numbers for services.
 *
 * Constant names exactly match the IDs defined in the Bluetooth SIG assigned numbers YAML file
 * (e.g. `org.bluetooth.service.heart_rate`). Combine with `Bluetooth.BaseUuid` (from
 * `kable-core`) to produce a full 128-bit [Uuid][kotlin.uuid.Uuid], for example:
 *
 * ```
 * val heartRateServiceUuid = Bluetooth.BaseUuid + org.bluetooth.service.heart_rate
 * println(heartRateServiceUuid) // Output: 0000180d-0000-1000-8000-00805f9b34fb
 * ```
 *
 * https://bitbucket.org/bluetooth-SIG/public/src/main/assigned_numbers/uuids/service_uuids.yaml
 */
public object service {
    /** GAP */
    public const val gap: Int = 0x1800

    /** GATT */
    public const val gatt: Int = 0x1801

    /** Immediate Alert */
    public const val immediate_alert: Int = 0x1802

    /** Link Loss */
    public const val link_loss: Int = 0x1803

    /** Tx Power */
    public const val tx_power: Int = 0x1804

    /** Current Time */
    public const val current_time: Int = 0x1805

    /** Reference Time Update */
    public const val reference_time_update: Int = 0x1806

    /** Next DST Change */
    public const val next_dst_change: Int = 0x1807

    /** Glucose */
    public const val glucose: Int = 0x1808

    /** Health Thermometer */
    public const val health_thermometer: Int = 0x1809

    /** Device Information */
    public const val device_information: Int = 0x180A

    /** Heart Rate */
    public const val heart_rate: Int = 0x180D

    /** Phone Alert Status */
    public const val phone_alert_status: Int = 0x180E

    /** Battery */
    public const val battery_service: Int = 0x180F

    /** Blood Pressure */
    public const val blood_pressure: Int = 0x1810

    /** Alert Notification */
    public const val alert_notification: Int = 0x1811

    /** Human Interface Device */
    public const val human_interface_device: Int = 0x1812

    /** Scan Parameters */
    public const val scan_parameters: Int = 0x1813

    /** Running Speed and Cadence */
    public const val running_speed_and_cadence: Int = 0x1814

    /** Automation IO */
    public const val automation_io: Int = 0x1815

    /** Cycling Speed and Cadence */
    public const val cycling_speed_and_cadence: Int = 0x1816

    /** Cycling Power */
    public const val cycling_power: Int = 0x1818

    /** Location and Navigation */
    public const val location_and_navigation: Int = 0x1819

    /** Environmental Sensing */
    public const val environmental_sensing: Int = 0x181A

    /** Body Composition */
    public const val body_composition: Int = 0x181B

    /** User Data */
    public const val user_data: Int = 0x181C

    /** Weight Scale */
    public const val weight_scale: Int = 0x181D

    /** Bond Management */
    public const val bond_management: Int = 0x181E

    /** Continuous Glucose Monitoring */
    public const val continuous_glucose_monitoring: Int = 0x181F

    /** Internet Protocol Support */
    public const val internet_protocol_support: Int = 0x1820

    /** Indoor Positioning */
    public const val indoor_positioning: Int = 0x1821

    /** Pulse Oximeter */
    public const val pulse_oximeter: Int = 0x1822

    /** HTTP Proxy */
    public const val http_proxy: Int = 0x1823

    /** Transport Discovery */
    public const val transport_discovery: Int = 0x1824

    /** Object Transfer */
    public const val object_transfer: Int = 0x1825

    /** Fitness Machine */
    public const val fitness_machine: Int = 0x1826

    /** Mesh Provisioning */
    public const val mesh_provisioning: Int = 0x1827

    /** Mesh Proxy */
    public const val mesh_proxy: Int = 0x1828

    /** Reconnection Configuration */
    public const val reconnection_configuration: Int = 0x1829

    /** Insulin Delivery */
    public const val insulin_delivery: Int = 0x183A

    /** Binary Sensor */
    public const val binary_sensor: Int = 0x183B

    /** Emergency Configuration */
    public const val emergency_configuration: Int = 0x183C

    /** Authorization Control */
    public const val authorization_control: Int = 0x183D

    /** Physical Activity Monitor */
    public const val physical_activity_monitor: Int = 0x183E

    /** Elapsed Time */
    public const val elapsed_time: Int = 0x183F

    /** Generic Health Sensor */
    public const val generic_health_sensor: Int = 0x1840

    /** Audio Input Control */
    public const val audio_input_control: Int = 0x1843

    /** Volume Control */
    public const val volume_control: Int = 0x1844

    /** Volume Offset Control */
    public const val volume_offset: Int = 0x1845

    /** Coordinated Set Identification */
    public const val coordinated_set_identification: Int = 0x1846

    /** Device Time */
    public const val device_time: Int = 0x1847

    /** Media Control */
    public const val media_control: Int = 0x1848

    /** Generic Media Control */
    public const val generic_media_control: Int = 0x1849

    /** Constant Tone Extension */
    public const val constant_tone_extension: Int = 0x184A

    /** Telephone Bearer */
    public const val telephone_bearer: Int = 0x184B

    /** Generic Telephone Bearer */
    public const val generic_telephone_bearer: Int = 0x184C

    /** Microphone Control */
    public const val microphone_control: Int = 0x184D

    /** Audio Stream Control */
    public const val audio_stream_control: Int = 0x184E

    /** Broadcast Audio Scan */
    public const val broadcast_audio_scan: Int = 0x184F

    /** Published Audio Capabilities */
    public const val published_audio_capabilities: Int = 0x1850

    /** Basic Audio Announcement */
    public const val basic_audio_announcement: Int = 0x1851

    /** Broadcast Audio Announcement */
    public const val broadcast_audio_announcement: Int = 0x1852

    /** Common Audio */
    public const val common_audio: Int = 0x1853

    /** Hearing Access */
    public const val hearing_access: Int = 0x1854

    /** Telephony and Media Audio */
    public const val telephony_and_media_audio: Int = 0x1855

    /** Public Broadcast Announcement */
    public const val public_broadcast_announcement: Int = 0x1856

    /** Electronic Shelf Label */
    public const val electronic_shelf_label: Int = 0x1857

    /** Gaming Audio */
    public const val gaming_audio: Int = 0x1858

    /** Mesh Proxy Solicitation */
    public const val mesh_proxy_solicitation: Int = 0x1859

    /** Industrial Measurement Device */
    public const val industrial_measurement_device: Int = 0x185A

    /** Ranging */
    public const val ranging: Int = 0x185B

    /** HID ISO */
    public const val hid_iso: Int = 0x185C

    /** Cookware */
    public const val cookware: Int = 0x185D

    /** Voice Assistant */
    public const val voice_assistant: Int = 0x185E

    /** Generic Voice Assistant */
    public const val generic_voice_assistant: Int = 0x185F
}

/**
 * Bluetooth SIG assigned numbers for characteristics.
 *
 * Constant names exactly match the IDs defined in the Bluetooth SIG assigned numbers YAML file
 * (e.g. `org.bluetooth.characteristic.heart_rate_measurement`).
 *
 * https://bitbucket.org/bluetooth-SIG/public/src/main/assigned_numbers/uuids/characteristic_uuids.yaml
 */
public object characteristic {
    public object gap {
        /** Device Name */
        public const val device_name: Int = 0x2A00

        /** Appearance */
        public const val appearance: Int = 0x2A01

        /** Peripheral Privacy Flag */
        public const val peripheral_privacy_flag: Int = 0x2A02

        /** Reconnection Address */
        public const val reconnection_address: Int = 0x2A03

        /** Peripheral Preferred Connection Parameters */
        public const val peripheral_preferred_connection_parameters: Int = 0x2A04

        /** Central Address Resolution */
        public const val central_address_resolution: Int = 0x2AA6
    }

    public object gatt {
        /** Service Changed */
        public const val service_changed: Int = 0x2A05
    }

    /** Alert Level */
    public const val alert_level: Int = 0x2A06

    /** Tx Power Level */
    public const val tx_power_level: Int = 0x2A07

    /** Date Time */
    public const val date_time: Int = 0x2A08

    /** Day of Week */
    public const val day_of_week: Int = 0x2A09

    /** Day Date Time */
    public const val day_date_time: Int = 0x2A0A

    /** Exact Time 256 */
    public const val exact_time_256: Int = 0x2A0C

    /** DST Offset */
    public const val dst_offset: Int = 0x2A0D

    /** Time Zone */
    public const val time_zone: Int = 0x2A0E

    /** Local Time Information */
    public const val local_time_information: Int = 0x2A0F

    /** Time with DST */
    public const val time_with_dst: Int = 0x2A11

    /** Time Accuracy */
    public const val time_accuracy: Int = 0x2A12

    /** Time Source */
    public const val time_source: Int = 0x2A13

    /** Reference Time Information */
    public const val reference_time_information: Int = 0x2A14

    /** Time Update Control Point */
    public const val time_update_control_point: Int = 0x2A16

    /** Time Update State */
    public const val time_update_state: Int = 0x2A17

    /** Glucose Measurement */
    public const val glucose_measurement: Int = 0x2A18

    /** Battery Level */
    public const val battery_level: Int = 0x2A19

    /** Temperature Measurement */
    public const val temperature_measurement: Int = 0x2A1C

    /** Temperature Type */
    public const val temperature_type: Int = 0x2A1D

    /** Intermediate Temperature */
    public const val intermediate_temperature: Int = 0x2A1E

    /** Measurement Interval */
    public const val measurement_interval: Int = 0x2A21

    /** Boot Keyboard Input Report */
    public const val boot_keyboard_input_report: Int = 0x2A22

    /** System ID */
    public const val system_id: Int = 0x2A23

    /** Model Number String */
    public const val model_number_string: Int = 0x2A24

    /** Serial Number String */
    public const val serial_number_string: Int = 0x2A25

    /** Firmware Revision String */
    public const val firmware_revision_string: Int = 0x2A26

    /** Hardware Revision String */
    public const val hardware_revision_string: Int = 0x2A27

    /** Software Revision String */
    public const val software_revision_string: Int = 0x2A28

    /** Manufacturer Name String */
    public const val manufacturer_name_string: Int = 0x2A29

    /** IEEE 11073-20601 Regulatory Certification Data List */
    public const val ieee_11073_20601_regulatory_certification_data_list: Int = 0x2A2A

    /** Current Time */
    public const val current_time: Int = 0x2A2B

    /** Magnetic Declination */
    public const val magnetic_declination: Int = 0x2A2C

    /** Scan Refresh */
    public const val scan_refresh: Int = 0x2A31

    /** Boot Keyboard Output Report */
    public const val boot_keyboard_output_report: Int = 0x2A32

    /** Boot Mouse Input Report */
    public const val boot_mouse_input_report: Int = 0x2A33

    /** Glucose Measurement Context */
    public const val glucose_measurement_context: Int = 0x2A34

    /** Blood Pressure Measurement */
    public const val blood_pressure_measurement: Int = 0x2A35

    /** Intermediate Cuff Pressure */
    public const val intermediate_cuff_pressure: Int = 0x2A36

    /** Heart Rate Measurement */
    public const val heart_rate_measurement: Int = 0x2A37

    /** Body Sensor Location */
    public const val body_sensor_location: Int = 0x2A38

    /** Heart Rate Control Point */
    public const val heart_rate_control_point: Int = 0x2A39

    /** Alert Status */
    public const val alert_status: Int = 0x2A3F

    /** Ringer Control Point */
    public const val ringer_control_point: Int = 0x2A40

    /** Ringer Setting */
    public const val ringer_setting: Int = 0x2A41

    /** Alert Category ID Bit Mask */
    public const val alert_category_id_bit_mask: Int = 0x2A42

    /** Alert Category ID */
    public const val alert_category_id: Int = 0x2A43

    /** Alert Notification Control Point */
    public const val alert_notification_control_point: Int = 0x2A44

    /** Unread Alert Status */
    public const val unread_alert_status: Int = 0x2A45

    /** New Alert */
    public const val new_alert: Int = 0x2A46

    /** Supported New Alert Category */
    public const val supported_new_alert_category: Int = 0x2A47

    /** Supported Unread Alert Category */
    public const val supported_unread_alert_category: Int = 0x2A48

    /** Blood Pressure Feature */
    public const val blood_pressure_feature: Int = 0x2A49

    /** HID Information */
    public const val hid_information: Int = 0x2A4A

    /** Report Map */
    public const val report_map: Int = 0x2A4B

    /** HID Control Point */
    public const val hid_control_point: Int = 0x2A4C

    /** Report */
    public const val report: Int = 0x2A4D

    /** Protocol Mode */
    public const val protocol_mode: Int = 0x2A4E

    /** Scan Interval Window */
    public const val scan_interval_window: Int = 0x2A4F

    /** PnP ID */
    public const val pnp_id: Int = 0x2A50

    /** Glucose Feature */
    public const val glucose_feature: Int = 0x2A51

    /** Record Access Control Point */
    public const val record_access_control_point: Int = 0x2A52

    /** RSC Measurement */
    public const val rsc_measurement: Int = 0x2A53

    /** RSC Feature */
    public const val rsc_feature: Int = 0x2A54

    /** SC Control Point */
    public const val sc_control_point: Int = 0x2A55

    /** Aggregate */
    public const val aggregate: Int = 0x2A5A

    /** CSC Measurement */
    public const val csc_measurement: Int = 0x2A5B

    /** CSC Feature */
    public const val csc_feature: Int = 0x2A5C

    /** Sensor Location */
    public const val sensor_location: Int = 0x2A5D

    /** PLX Spot-Check Measurement */
    public const val plx_spot_check_measurement: Int = 0x2A5E

    /** PLX Continuous Measurement */
    public const val plx_continuous_measurement: Int = 0x2A5F

    /** PLX Features */
    public const val plx_features: Int = 0x2A60

    /** Cycling Power Measurement */
    public const val cycling_power_measurement: Int = 0x2A63

    /** Cycling Power Vector */
    public const val cycling_power_vector: Int = 0x2A64

    /** Cycling Power Feature */
    public const val cycling_power_feature: Int = 0x2A65

    /** Cycling Power Control Point */
    public const val cycling_power_control_point: Int = 0x2A66

    /** Location and Speed */
    public const val location_and_speed: Int = 0x2A67

    /** Navigation */
    public const val navigation: Int = 0x2A68

    /** Position Quality */
    public const val position_quality: Int = 0x2A69

    /** LN Feature */
    public const val ln_feature: Int = 0x2A6A

    /** LN Control Point */
    public const val ln_control_point: Int = 0x2A6B

    /** Elevation */
    public const val elevation: Int = 0x2A6C

    /** Pressure */
    public const val pressure: Int = 0x2A6D

    /** Temperature */
    public const val temperature: Int = 0x2A6E

    /** Humidity */
    public const val humidity: Int = 0x2A6F

    /** True Wind Speed */
    public const val true_wind_speed: Int = 0x2A70

    /** True Wind Direction */
    public const val true_wind_direction: Int = 0x2A71

    /** Apparent Wind Speed */
    public const val apparent_wind_speed: Int = 0x2A72

    /** Apparent Wind Direction */
    public const val apparent_wind_direction: Int = 0x2A73

    /** Gust Factor */
    public const val gust_factor: Int = 0x2A74

    /** Pollen Concentration */
    public const val pollen_concentration: Int = 0x2A75

    /** UV Index */
    public const val uv_index: Int = 0x2A76

    /** Irradiance */
    public const val irradiance: Int = 0x2A77

    /** Rainfall */
    public const val rainfall: Int = 0x2A78

    /** Wind Chill */
    public const val wind_chill: Int = 0x2A79

    /** Heat Index */
    public const val heat_index: Int = 0x2A7A

    /** Dew Point */
    public const val dew_point: Int = 0x2A7B

    /** Descriptor Value Changed */
    public const val descriptor_value_changed: Int = 0x2A7D

    /** Aerobic Heart Rate Lower Limit */
    public const val aerobic_heart_rate_lower_limit: Int = 0x2A7E

    /** Aerobic Threshold */
    public const val aerobic_threshold: Int = 0x2A7F

    /** Age */
    public const val age: Int = 0x2A80

    /** Anaerobic Heart Rate Lower Limit */
    public const val anaerobic_heart_rate_lower_limit: Int = 0x2A81

    /** Anaerobic Heart Rate Upper Limit */
    public const val anaerobic_heart_rate_upper_limit: Int = 0x2A82

    /** Anaerobic Threshold */
    public const val anaerobic_threshold: Int = 0x2A83

    /** Aerobic Heart Rate Upper Limit */
    public const val aerobic_heart_rate_upper_limit: Int = 0x2A84

    /** Date of Birth */
    public const val date_of_birth: Int = 0x2A85

    /** Date of Threshold Assessment */
    public const val date_of_threshold_assessment: Int = 0x2A86

    /** Email Address */
    public const val email_address: Int = 0x2A87

    /** Fat Burn Heart Rate Lower Limit */
    public const val fat_burn_heart_rate_lower_limit: Int = 0x2A88

    /** Fat Burn Heart Rate Upper Limit */
    public const val fat_burn_heart_rate_upper_limit: Int = 0x2A89

    /** First Name */
    public const val first_name: Int = 0x2A8A

    /** Five Zone Heart Rate Limits */
    public const val five_zone_heart_rate_limits: Int = 0x2A8B

    /** Gender */
    public const val gender: Int = 0x2A8C

    /** Heart Rate Max */
    public const val heart_rate_max: Int = 0x2A8D

    /** Height */
    public const val height: Int = 0x2A8E

    /** Hip Circumference */
    public const val hip_circumference: Int = 0x2A8F

    /** Last Name */
    public const val last_name: Int = 0x2A90

    /** Maximum Recommended Heart Rate */
    public const val maximum_recommended_heart_rate: Int = 0x2A91

    /** Resting Heart Rate */
    public const val resting_heart_rate: Int = 0x2A92

    /** Sport Type for Aerobic and Anaerobic Thresholds */
    public const val sport_type_for_aerobic_and_anaerobic_thresholds: Int = 0x2A93

    /** Three Zone Heart Rate Limits */
    public const val three_zone_heart_rate_limits: Int = 0x2A94

    /** Two Zone Heart Rate Limits */
    public const val two_zone_heart_rate_limits: Int = 0x2A95

    /** VO2 Max */
    public const val vo2_max: Int = 0x2A96

    /** Waist Circumference */
    public const val waist_circumference: Int = 0x2A97

    /** Weight */
    public const val weight: Int = 0x2A98

    /** Database Change Increment */
    public const val database_change_increment: Int = 0x2A99

    /** User Index */
    public const val user_index: Int = 0x2A9A

    /** Body Composition Feature */
    public const val body_composition_feature: Int = 0x2A9B

    /** Body Composition Measurement */
    public const val body_composition_measurement: Int = 0x2A9C

    /** Weight Measurement */
    public const val weight_measurement: Int = 0x2A9D

    /** Weight Scale Feature */
    public const val weight_scale_feature: Int = 0x2A9E

    /** User Control Point */
    public const val user_control_point: Int = 0x2A9F

    /** Magnetic Flux Density - 2D */
    public const val magnetic_flux_density_2d: Int = 0x2AA0

    /** Magnetic Flux Density - 3D */
    public const val magnetic_flux_density_3d: Int = 0x2AA1

    /** Language */
    public const val language: Int = 0x2AA2

    /** Barometric Pressure Trend */
    public const val barometric_pressure_trend: Int = 0x2AA3

    /** Bond Management Control Point */
    public const val bond_management_control_point: Int = 0x2AA4

    /** Bond Management Feature */
    public const val bond_management_feature: Int = 0x2AA5

    /** CGM Measurement */
    public const val cgm_measurement: Int = 0x2AA7

    /** CGM Feature */
    public const val cgm_feature: Int = 0x2AA8

    /** CGM Status */
    public const val cgm_status: Int = 0x2AA9

    /** CGM Session Start Time */
    public const val cgm_session_start_time: Int = 0x2AAA

    /** CGM Session Run Time */
    public const val cgm_session_run_time: Int = 0x2AAB

    /** CGM Specific Ops Control Point */
    public const val cgm_specific_ops_control_point: Int = 0x2AAC

    /** Indoor Positioning Configuration */
    public const val indoor_positioning_configuration: Int = 0x2AAD

    /** Latitude */
    public const val latitude: Int = 0x2AAE

    /** Longitude */
    public const val longitude: Int = 0x2AAF

    /** Local North Coordinate */
    public const val local_north_coordinate: Int = 0x2AB0

    /** Local East Coordinate */
    public const val local_east_coordinate: Int = 0x2AB1

    /** Floor Number */
    public const val floor_number: Int = 0x2AB2

    /** Altitude */
    public const val altitude: Int = 0x2AB3

    /** Uncertainty */
    public const val uncertainty: Int = 0x2AB4

    /** Location Name */
    public const val location_name: Int = 0x2AB5

    /** URI */
    public const val uri: Int = 0x2AB6

    /** HTTP Headers */
    public const val http_headers: Int = 0x2AB7

    /** HTTP Status Code */
    public const val http_status_code: Int = 0x2AB8

    /** HTTP Entity Body */
    public const val http_entity_body: Int = 0x2AB9

    /** HTTP Control Point */
    public const val http_control_point: Int = 0x2ABA

    /** HTTPS Security */
    public const val https_security: Int = 0x2ABB

    /** TDS Control Point */
    public const val tds_control_point: Int = 0x2ABC

    /** OTS Feature */
    public const val ots_feature: Int = 0x2ABD

    /** Object Name */
    public const val object_name: Int = 0x2ABE

    /** Object Type */
    public const val object_type: Int = 0x2ABF

    /** Object Size */
    public const val object_size: Int = 0x2AC0

    /** Object First-Created */
    public const val object_first_created: Int = 0x2AC1

    /** Object Last-Modified */
    public const val object_last_modified: Int = 0x2AC2

    /** Object ID */
    public const val object_id: Int = 0x2AC3

    /** Object Properties */
    public const val object_properties: Int = 0x2AC4

    /** Object Action Control Point */
    public const val object_action_control_point: Int = 0x2AC5

    /** Object List Control Point */
    public const val object_list_control_point: Int = 0x2AC6

    /** Object List Filter */
    public const val object_list_filter: Int = 0x2AC7

    /** Object Changed */
    public const val object_changed: Int = 0x2AC8

    /** Resolvable Private Address Only */
    public const val resolvable_private_address_only: Int = 0x2AC9

    /** Fitness Machine Feature */
    public const val fitness_machine_feature: Int = 0x2ACC

    /** Treadmill Data */
    public const val treadmill_data: Int = 0x2ACD

    /** Cross Trainer Data */
    public const val cross_trainer_data: Int = 0x2ACE

    /** Step Climber Data */
    public const val step_climber_data: Int = 0x2ACF

    /** Stair Climber Data */
    public const val stair_climber_data: Int = 0x2AD0

    /** Rower Data */
    public const val rower_data: Int = 0x2AD1

    /** Indoor Bike Data */
    public const val indoor_bike_data: Int = 0x2AD2

    /** Training Status */
    public const val training_status: Int = 0x2AD3

    /** Supported Speed Range */
    public const val supported_speed_range: Int = 0x2AD4

    /** Supported Inclination Range */
    public const val supported_inclination_range: Int = 0x2AD5

    /** Supported Resistance Level Range */
    public const val supported_resistance_level_range: Int = 0x2AD6

    /** Supported Heart Rate Range */
    public const val supported_heart_rate_range: Int = 0x2AD7

    /** Supported Power Range */
    public const val supported_power_range: Int = 0x2AD8

    /** Fitness Machine Control Point */
    public const val fitness_machine_control_point: Int = 0x2AD9

    /** Fitness Machine Status */
    public const val fitness_machine_status: Int = 0x2ADA

    /** Mesh Provisioning Data In */
    public const val mesh_provisioning_data_in: Int = 0x2ADB

    /** Mesh Provisioning Data Out */
    public const val mesh_provisioning_data_out: Int = 0x2ADC

    /** Mesh Proxy Data In */
    public const val mesh_proxy_data_in: Int = 0x2ADD

    /** Mesh Proxy Data Out */
    public const val mesh_proxy_data_out: Int = 0x2ADE

    /** Average Current */
    public const val average_current: Int = 0x2AE0

    /** Average Voltage */
    public const val average_voltage: Int = 0x2AE1

    /** Boolean */
    public const val boolean: Int = 0x2AE2

    /** Chromatic Distance from Planckian */
    public const val chromatic_distance_from_planckian: Int = 0x2AE3

    /** Chromaticity Coordinates */
    public const val chromaticity_coordinates: Int = 0x2AE4

    /** Chromaticity in CCT and Duv Values */
    public const val chromaticity_in_cct_and_duv_values: Int = 0x2AE5

    /** Chromaticity Tolerance */
    public const val chromaticity_tolerance: Int = 0x2AE6

    /** CIE 13.3-1995 Color Rendering Index */
    public const val cie_13_3_1995_color_rendering_index: Int = 0x2AE7

    /** Coefficient */
    public const val coefficient: Int = 0x2AE8

    /** Correlated Color Temperature */
    public const val correlated_color_temperature: Int = 0x2AE9

    /** Count 16 */
    public const val count_16: Int = 0x2AEA

    /** Count 24 */
    public const val count_24: Int = 0x2AEB

    /** Country Code */
    public const val country_code: Int = 0x2AEC

    /** Date UTC */
    public const val date_utc: Int = 0x2AED

    /** Electric Current */
    public const val electric_current: Int = 0x2AEE

    /** Electric Current Range */
    public const val electric_current_range: Int = 0x2AEF

    /** Electric Current Specification */
    public const val electric_current_specification: Int = 0x2AF0

    /** Electric Current Statistics */
    public const val electric_current_statistics: Int = 0x2AF1

    /** Energy */
    public const val energy: Int = 0x2AF2

    /** Energy in a Period of Day */
    public const val energy_in_a_period_of_day: Int = 0x2AF3

    /** Event Statistics */
    public const val event_statistics: Int = 0x2AF4

    /** Fixed String 16 */
    public const val fixed_string_16: Int = 0x2AF5

    /** Fixed String 24 */
    public const val fixed_string_24: Int = 0x2AF6

    /** Fixed String 36 */
    public const val fixed_string_36: Int = 0x2AF7

    /** Fixed String 8 */
    public const val fixed_string_8: Int = 0x2AF8

    /** Generic Level */
    public const val generic_level: Int = 0x2AF9

    /** Global Trade Item Number */
    public const val global_trade_item_number: Int = 0x2AFA

    /** Illuminance */
    public const val illuminance: Int = 0x2AFB

    /** Luminous Efficacy */
    public const val luminous_efficacy: Int = 0x2AFC

    /** Luminous Energy */
    public const val luminous_energy: Int = 0x2AFD

    /** Luminous Exposure */
    public const val luminous_exposure: Int = 0x2AFE

    /** Luminous Flux */
    public const val luminous_flux: Int = 0x2AFF

    /** Luminous Flux Range */
    public const val luminous_flux_range: Int = 0x2B00

    /** Luminous Intensity */
    public const val luminous_intensity: Int = 0x2B01

    /** Mass Flow */
    public const val mass_flow: Int = 0x2B02

    /** Perceived Lightness */
    public const val perceived_lightness: Int = 0x2B03

    /** Percentage 8 */
    public const val percentage_8: Int = 0x2B04

    /** Power */
    public const val power: Int = 0x2B05

    /** Power Specification */
    public const val power_specification: Int = 0x2B06

    /** Relative Runtime in a Current Range */
    public const val relative_runtime_in_a_current_range: Int = 0x2B07

    /** Relative Runtime in a Generic Level Range */
    public const val relative_runtime_in_a_generic_level_range: Int = 0x2B08

    /** Relative Value in a Voltage Range */
    public const val relative_value_in_a_voltage_range: Int = 0x2B09

    /** Relative Value in an Illuminance Range */
    public const val relative_value_in_an_illuminance_range: Int = 0x2B0A

    /** Relative Value in a Period of Day */
    public const val relative_value_in_a_period_of_day: Int = 0x2B0B

    /** Relative Value in a Temperature Range */
    public const val relative_value_in_a_temperature_range: Int = 0x2B0C

    /** Temperature 8 */
    public const val temperature_8: Int = 0x2B0D

    /** Temperature 8 in a Period of Day */
    public const val temperature_8_in_a_period_of_day: Int = 0x2B0E

    /** Temperature 8 Statistics */
    public const val temperature_8_statistics: Int = 0x2B0F

    /** Temperature Range */
    public const val temperature_range: Int = 0x2B10

    /** Temperature Statistics */
    public const val temperature_statistics: Int = 0x2B11

    /** Time Decihour 8 */
    public const val time_decihour_8: Int = 0x2B12

    /** Time Exponential 8 */
    public const val time_exponential_8: Int = 0x2B13

    /** Time Hour 24 */
    public const val time_hour_24: Int = 0x2B14

    /** Time Millisecond 24 */
    public const val time_millisecond_24: Int = 0x2B15

    /** Time Second 16 */
    public const val time_second_16: Int = 0x2B16

    /** Time Second 8 */
    public const val time_second_8: Int = 0x2B17

    /** Voltage */
    public const val voltage: Int = 0x2B18

    /** Voltage Specification */
    public const val voltage_specification: Int = 0x2B19

    /** Voltage Statistics */
    public const val voltage_statistics: Int = 0x2B1A

    /** Volume Flow */
    public const val volume_flow: Int = 0x2B1B

    /** Chromaticity Coordinate */
    public const val chromaticity_coordinate: Int = 0x2B1C

    /** RC Feature */
    public const val rc_feature: Int = 0x2B1D

    /** RC Settings */
    public const val rc_settings: Int = 0x2B1E

    /** Reconnection Configuration Control Point */
    public const val reconnection_configuration_control_point: Int = 0x2B1F

    /** IDD Status Changed */
    public const val idd_status_changed: Int = 0x2B20

    /** IDD Status */
    public const val idd_status: Int = 0x2B21

    /** IDD Annunciation Status */
    public const val idd_annunciation_status: Int = 0x2B22

    /** IDD Features */
    public const val idd_features: Int = 0x2B23

    /** IDD Status Reader Control Point */
    public const val idd_status_reader_control_point: Int = 0x2B24

    /** IDD Command Control Point */
    public const val idd_command_control_point: Int = 0x2B25

    /** IDD Command Data */
    public const val idd_command_data: Int = 0x2B26

    /** IDD Record Access Control Point */
    public const val idd_record_access_control_point: Int = 0x2B27

    /** IDD History Data */
    public const val idd_history_data: Int = 0x2B28

    /** Client Supported Features */
    public const val client_supported_features: Int = 0x2B29

    /** Database Hash */
    public const val database_hash: Int = 0x2B2A

    /** BSS Control Point */
    public const val bss_control_point: Int = 0x2B2B

    /** BSS Response */
    public const val bss_response: Int = 0x2B2C

    /** Emergency ID */
    public const val emergency_id: Int = 0x2B2D

    /** Emergency Text */
    public const val emergency_text: Int = 0x2B2E

    /** ACS Status */
    public const val acs_status: Int = 0x2B2F

    /** ACS Data In */
    public const val acs_data_in: Int = 0x2B30

    /** ACS Data Out Notify */
    public const val acs_data_out_notify: Int = 0x2B31

    /** ACS Data Out Indicate */
    public const val acs_data_out_indicate: Int = 0x2B32

    /** ACS Control Point */
    public const val acs_control_point: Int = 0x2B33

    /** Enhanced Blood Pressure Measurement */
    public const val enhanced_blood_pressure_measurement: Int = 0x2B34

    /** Enhanced Intermediate Cuff Pressure */
    public const val enhanced_intermediate_cuff_pressure: Int = 0x2B35

    /** Blood Pressure Record */
    public const val blood_pressure_record: Int = 0x2B36

    /** Registered User */
    public const val registered_user: Int = 0x2B37

    /** BR-EDR Handover Data */
    public const val br_edr_handover_data: Int = 0x2B38

    /** Bluetooth SIG Data */
    public const val bluetooth_sig_data: Int = 0x2B39

    /** Server Supported Features */
    public const val server_supported_features: Int = 0x2B3A

    /** Physical Activity Monitor Features */
    public const val physical_activity_monitor_features: Int = 0x2B3B

    /** General Activity Instantaneous Data */
    public const val general_activity_instantaneous_data: Int = 0x2B3C

    /** General Activity Summary Data */
    public const val general_activity_summary_data: Int = 0x2B3D

    /** CardioRespiratory Activity Instantaneous Data */
    public const val cardiorespiratory_activity_instantaneous_data: Int = 0x2B3E

    /** CardioRespiratory Activity Summary Data */
    public const val cardiorespiratory_activity_summary_data: Int = 0x2B3F

    /** Step Counter Activity Summary Data */
    public const val step_counter_activity_summary_data: Int = 0x2B40

    /** Sleep Activity Instantaneous Data */
    public const val sleep_activity_instantaneous_data: Int = 0x2B41

    /** Sleep Activity Summary Data */
    public const val sleep_activity_summary_data: Int = 0x2B42

    /** Physical Activity Monitor Control Point */
    public const val physical_activity_monitor_control_point: Int = 0x2B43

    /** Physical Activity Current Session */
    public const val physical_activity_current_session: Int = 0x2B44

    /** Physical Activity Session Descriptor */
    public const val physical_activity_session_descriptor: Int = 0x2B45

    /** Preferred Units */
    public const val preferred_units: Int = 0x2B46

    /** High Resolution Height */
    public const val high_resolution_height: Int = 0x2B47

    /** Middle Name */
    public const val middle_name: Int = 0x2B48

    /** Stride Length */
    public const val stride_length: Int = 0x2B49

    /** Handedness */
    public const val handedness: Int = 0x2B4A

    /** Device Wearing Position */
    public const val device_wearing_position: Int = 0x2B4B

    /** Four Zone Heart Rate Limits */
    public const val four_zone_heart_rate_limits: Int = 0x2B4C

    /** High Intensity Exercise Threshold */
    public const val high_intensity_exercise_threshold: Int = 0x2B4D

    /** Activity Goal */
    public const val activity_goal: Int = 0x2B4E

    /** Sedentary Interval Notification */
    public const val sedentary_interval_notification: Int = 0x2B4F

    /** Caloric Intake */
    public const val caloric_intake: Int = 0x2B50

    /** TMAP Role */
    public const val tmap_role: Int = 0x2B51

    /** Audio Input State */
    public const val audio_input_state: Int = 0x2B77

    /** Gain Settings Attribute */
    public const val gain_settings_attribute: Int = 0x2B78

    /** Audio Input Type */
    public const val audio_input_type: Int = 0x2B79

    /** Audio Input Status */
    public const val audio_input_status: Int = 0x2B7A

    /** Audio Input Control Point */
    public const val audio_input_control_point: Int = 0x2B7B

    /** Audio Input Description */
    public const val audio_input_description: Int = 0x2B7C

    /** Volume State */
    public const val volume_state: Int = 0x2B7D

    /** Volume Control Point */
    public const val volume_control_point: Int = 0x2B7E

    /** Volume Flags */
    public const val volume_flags: Int = 0x2B7F

    /** Volume Offset State */
    public const val volume_offset_state: Int = 0x2B80

    /** Audio Location */
    public const val audio_location: Int = 0x2B81

    /** Volume Offset Control Point */
    public const val volume_offset_control_point: Int = 0x2B82

    /** Audio Output Description */
    public const val audio_output_description: Int = 0x2B83

    /** Set Identity Resolving Key */
    public const val set_identity_resolving_key: Int = 0x2B84

    /** Coordinated Set Size */
    public const val size_characteristic: Int = 0x2B85

    /** Set Member Lock */
    public const val lock_characteristic: Int = 0x2B86

    /** Set Member Rank */
    public const val rank_characteristic: Int = 0x2B87

    /** Encrypted Data Key Material */
    public const val encrypted_data_key_material: Int = 0x2B88

    /** Apparent Energy 32 */
    public const val apparent_energy_32: Int = 0x2B89

    /** Apparent Power */
    public const val apparent_power: Int = 0x2B8A

    /** Live Health Observations */
    public const val live_health_observations: Int = 0x2B8B

    /** CO\\textsubscript{2} Concentration */
    public const val co2_concentration: Int = 0x2B8C

    /** Cosine of the Angle */
    public const val cosine_of_the_angle: Int = 0x2B8D

    /** Device Time Feature */
    public const val device_time_feature: Int = 0x2B8E

    /** Device Time Parameters */
    public const val device_time_parameters: Int = 0x2B8F

    /** Device Time */
    public const val device_time: Int = 0x2B90

    /** Device Time Control Point */
    public const val device_time_control_point: Int = 0x2B91

    /** Time Change Log Data */
    public const val time_change_log_data: Int = 0x2B92

    /** Media Player Name */
    public const val media_player_name: Int = 0x2B93

    /** Media Player Icon Object ID */
    public const val media_player_icon_object_id: Int = 0x2B94

    /** Media Player Icon URL */
    public const val media_player_icon_url: Int = 0x2B95

    /** Track Changed */
    public const val track_changed: Int = 0x2B96

    /** Track Title */
    public const val track_title: Int = 0x2B97

    /** Track Duration */
    public const val track_duration: Int = 0x2B98

    /** Track Position */
    public const val track_position: Int = 0x2B99

    /** Playback Speed */
    public const val playback_speed: Int = 0x2B9A

    /** Seeking Speed */
    public const val seeking_speed: Int = 0x2B9B

    /** Current Track Segments Object ID */
    public const val current_track_segments_object_id: Int = 0x2B9C

    /** Current Track Object ID */
    public const val current_track_object_id: Int = 0x2B9D

    /** Next Track Object ID */
    public const val next_track_object_id: Int = 0x2B9E

    /** Parent Group Object ID */
    public const val parent_group_object_id: Int = 0x2B9F

    /** Current Group Object ID */
    public const val current_group_object_id: Int = 0x2BA0

    /** Playing Order */
    public const val playing_order: Int = 0x2BA1

    /** Playing Orders Supported */
    public const val playing_orders_supported: Int = 0x2BA2

    /** Media State */
    public const val media_state: Int = 0x2BA3

    /** Media Control Point */
    public const val media_control_point: Int = 0x2BA4

    /** Media Control Point Opcodes Supported */
    public const val media_control_point_opcodes_supported: Int = 0x2BA5

    /** Search Results Object ID */
    public const val search_results_object_id: Int = 0x2BA6

    /** Search Control Point */
    public const val search_control_point: Int = 0x2BA7

    /** Energy 32 */
    public const val energy_32: Int = 0x2BA8

    /** Constant Tone Extension Enable */
    public const val constant_tone_extension_enable: Int = 0x2BAD

    /** Advertising Constant Tone Extension Minimum Length */
    public const val advertising_constant_tone_extension_minimum_length: Int = 0x2BAE

    /** Advertising Constant Tone Extension Minimum Transmit Count */
    public const val advertising_constant_tone_extension_minimum_transmit_count: Int = 0x2BAF

    /** Advertising Constant Tone Extension Transmit Duration */
    public const val advertising_constant_tone_extension_transmit_duration: Int = 0x2BB0

    /** Advertising Constant Tone Extension Interval */
    public const val advertising_constant_tone_extension_interval: Int = 0x2BB1

    /** Advertising Constant Tone Extension PHY */
    public const val advertising_constant_tone_extension_phy: Int = 0x2BB2

    /** Bearer Provider Name */
    public const val bearer_provider_name: Int = 0x2BB3

    /** Bearer UCI */
    public const val bearer_uci: Int = 0x2BB4

    /** Bearer Technology */
    public const val bearer_technology: Int = 0x2BB5

    /** Bearer URI Schemes Supported List */
    public const val bearer_uri_schemes_supported_list: Int = 0x2BB6

    /** Bearer Signal Strength */
    public const val bearer_signal_strength: Int = 0x2BB7

    /** Bearer Signal Strength Reporting Interval */
    public const val bearer_signal_strength_reporting_interval: Int = 0x2BB8

    /** Bearer List Current Calls */
    public const val bearer_list_current_calls: Int = 0x2BB9

    /** Content Control ID */
    public const val content_control_id: Int = 0x2BBA

    /** Status Flags */
    public const val status_flags: Int = 0x2BBB

    /** Incoming Call Target Bearer URI */
    public const val incoming_call_target_bearer_uri: Int = 0x2BBC

    /** Call State */
    public const val call_state: Int = 0x2BBD

    /** Call Control Point */
    public const val call_control_point: Int = 0x2BBE

    /** Call Control Point Optional Opcodes */
    public const val call_control_point_optional_opcodes: Int = 0x2BBF

    /** Termination Reason */
    public const val termination_reason: Int = 0x2BC0

    /** Incoming Call */
    public const val incoming_call: Int = 0x2BC1

    /** Call Friendly Name */
    public const val call_friendly_name: Int = 0x2BC2

    /** Mute */
    public const val mute: Int = 0x2BC3

    /** Sink ASE */
    public const val sink_ase: Int = 0x2BC4

    /** Source ASE */
    public const val source_ase: Int = 0x2BC5

    /** ASE Control Point */
    public const val ase_control_point: Int = 0x2BC6

    /** Broadcast Audio Scan Control Point */
    public const val broadcast_audio_scan_control_point: Int = 0x2BC7

    /** Broadcast Receive State */
    public const val broadcast_receive_state: Int = 0x2BC8

    /** Sink PAC */
    public const val sink_pac: Int = 0x2BC9

    /** Sink Audio Locations */
    public const val sink_audio_locations: Int = 0x2BCA

    /** Source PAC */
    public const val source_pac: Int = 0x2BCB

    /** Source Audio Locations */
    public const val source_audio_locations: Int = 0x2BCC

    /** Available Audio Contexts */
    public const val available_audio_contexts: Int = 0x2BCD

    /** Supported Audio Contexts */
    public const val supported_audio_contexts: Int = 0x2BCE

    /** Ammonia Concentration */
    public const val ammonia_concentration: Int = 0x2BCF

    /** Carbon Monoxide Concentration */
    public const val carbon_monoxide_concentration: Int = 0x2BD0

    /** Methane Concentration */
    public const val methane_concentration: Int = 0x2BD1

    /** Nitrogen Dioxide Concentration */
    public const val nitrogen_dioxide_concentration: Int = 0x2BD2

    /** Non-Methane Volatile Organic Compounds Concentration */
    public const val `non-methane_volatile_organic_compounds_concentration`: Int = 0x2BD3

    /** Ozone Concentration */
    public const val ozone_concentration: Int = 0x2BD4

    /** Particulate Matter - PM1 Concentration */
    public const val particulate_matter_pm1_concentration: Int = 0x2BD5

    /** Particulate Matter - PM2.5 Concentration */
    public const val particulate_matter_pm2_5_concentration: Int = 0x2BD6

    /** Particulate Matter - PM10 Concentration */
    public const val particulate_matter_pm10_concentration: Int = 0x2BD7

    /** Sulfur Dioxide Concentration */
    public const val sulfur_dioxide_concentration: Int = 0x2BD8

    /** Sulfur Hexafluoride Concentration */
    public const val sulfur_hexafluoride_concentration: Int = 0x2BD9

    /** Hearing Aid Features */
    public const val hearing_aid_features: Int = 0x2BDA

    /** Hearing Aid Preset Control Point */
    public const val hearing_aid_preset_control_point: Int = 0x2BDB

    /** Active Preset Index */
    public const val active_preset_index: Int = 0x2BDC

    /** Stored Health Observations */
    public const val stored_health_observations: Int = 0x2BDD

    /** Fixed String 64 */
    public const val fixed_string_64: Int = 0x2BDE

    /** High Temperature */
    public const val high_temperature: Int = 0x2BDF

    /** High Voltage */
    public const val high_voltage: Int = 0x2BE0

    /** Light Distribution */
    public const val light_distribution: Int = 0x2BE1

    /** Light Output */
    public const val light_output: Int = 0x2BE2

    /** Light Source Type */
    public const val light_source_type: Int = 0x2BE3

    /** Noise */
    public const val noise: Int = 0x2BE4

    /** Relative Runtime in a Correlated Color Temperature Range */
    public const val relative_runtime_in_a_correlated_color_temperature_range: Int = 0x2BE5

    /** Time Second 32 */
    public const val time_second_32: Int = 0x2BE6

    /** VOC Concentration */
    public const val voc_concentration: Int = 0x2BE7

    /** Voltage Frequency */
    public const val voltage_frequency: Int = 0x2BE8

    /** Battery Critical Status */
    public const val battery_critical_status: Int = 0x2BE9

    /** Battery Health Status */
    public const val battery_health_status: Int = 0x2BEA

    /** Battery Health Information */
    public const val battery_health_information: Int = 0x2BEB

    /** Battery Information */
    public const val battery_information: Int = 0x2BEC

    /** Battery Level Status */
    public const val battery_level_status: Int = 0x2BED

    /** Battery Time Status */
    public const val battery_time_status: Int = 0x2BEE

    /** Estimated Service Date */
    public const val estimated_service_date: Int = 0x2BEF

    /** Battery Energy Status */
    public const val battery_energy_status: Int = 0x2BF0

    /** Observation Schedule Changed */
    public const val observation_schedule_changed: Int = 0x2BF1

    /** Elapsed Time */
    public const val elapsed_time: Int = 0x2BF2

    /** Health Sensor Features */
    public const val health_sensor_features: Int = 0x2BF3

    /** GHS Control Point */
    public const val ghs_control_point: Int = 0x2BF4

    /** LE GATT Security Levels */
    public const val le_gatt_security_levels: Int = 0x2BF5

    /** ESL Address */
    public const val esl_address: Int = 0x2BF6

    /** AP Sync Key Material */
    public const val ap_sync_key_material: Int = 0x2BF7

    /** ESL Response Key Material */
    public const val esl_response_key_material: Int = 0x2BF8

    /** ESL Current Absolute Time */
    public const val esl_current_absolute_time: Int = 0x2BF9

    /** ESL Display Information */
    public const val esl_display_information: Int = 0x2BFA

    /** ESL Image Information */
    public const val esl_image_information: Int = 0x2BFB

    /** ESL Sensor Information */
    public const val esl_sensor_information: Int = 0x2BFC

    /** ESL LED Information */
    public const val esl_led_information: Int = 0x2BFD

    /** ESL Control Point */
    public const val esl_control_point: Int = 0x2BFE

    /** UDI for Medical Devices */
    public const val udi_for_medical_devices: Int = 0x2BFF

    /** GMAP Role */
    public const val gmap_role: Int = 0x2C00

    /** UGG Features */
    public const val ugg_features: Int = 0x2C01

    /** UGT Features */
    public const val ugt_features: Int = 0x2C02

    /** BGS Features */
    public const val bgs_features: Int = 0x2C03

    /** BGR Features */
    public const val bgr_features: Int = 0x2C04

    /** Percentage 8 Steps */
    public const val percentage_8_steps: Int = 0x2C05

    /** Acceleration */
    public const val acceleration: Int = 0x2C06

    /** Force */
    public const val force: Int = 0x2C07

    /** Linear Position */
    public const val linear_position: Int = 0x2C08

    /** Rotational Speed */
    public const val rotational_speed: Int = 0x2C09

    /** Length */
    public const val length: Int = 0x2C0A

    /** Torque */
    public const val torque: Int = 0x2C0B

    /** IMD Status */
    public const val imd_status: Int = 0x2C0C

    /** IMDS Descriptor Value Changed */
    public const val imds_descriptor_value_changed: Int = 0x2C0D

    /** First Use Date */
    public const val first_use_date: Int = 0x2C0E

    /** Life Cycle Data */
    public const val life_cycle_data: Int = 0x2C0F

    /** Work Cycle Data */
    public const val work_cycle_data: Int = 0x2C10

    /** Service Cycle Data */
    public const val service_cycle_data: Int = 0x2C11

    /** IMD Control */
    public const val imd_control: Int = 0x2C12

    /** IMD Historical Data */
    public const val imd_historical_data: Int = 0x2C13

    /** RAS Features */
    public const val ras_features: Int = 0x2C14

    /** Real-time Ranging Data */
    public const val `real-time_ranging_data`: Int = 0x2C15

    /** On-demand Ranging Data */
    public const val `on-demand_ranging_data`: Int = 0x2C16

    /** RAS Control Point */
    public const val ras_control_point: Int = 0x2C17

    /** Ranging Data Ready */
    public const val ranging_data_ready: Int = 0x2C18

    /** Ranging Data Overwritten */
    public const val ranging_data_overwritten: Int = 0x2C19

    /** Coordinated Set Name */
    public const val coordinated_set_name: Int = 0x2C1A

    /** Humidity 8 */
    public const val humidity_8: Int = 0x2C1B

    /** Illuminance 16 */
    public const val illuminance_16: Int = 0x2C1C

    /** Acceleration - 3D */
    public const val acceleration_3d: Int = 0x2C1D

    /** Precise Acceleration - 3D */
    public const val precise_acceleration_3d: Int = 0x2C1E

    /** Acceleration Detection Status */
    public const val acceleration_detection_status: Int = 0x2C1F

    /** Door/Window Status */
    public const val door_window_status: Int = 0x2C20

    /** Pushbutton Status 8 */
    public const val pushbutton_status_8: Int = 0x2C21

    /** Contact Status 8 */
    public const val contact_status_8: Int = 0x2C22

    /** HID ISO Properties */
    public const val hid_iso_properties: Int = 0x2C23

    /** LE HID Operation Mode */
    public const val le_hid_operation_mode: Int = 0x2C24

    /** Cookware Description */
    public const val cookware_description: Int = 0x2C25

    /** Recipe Control */
    public const val recipe_control: Int = 0x2C26

    /** Recipe Parameters */
    public const val recipe_parameters: Int = 0x2C27

    /** Cooking Step Status */
    public const val cooking_step_status: Int = 0x2C28

    /** Cooking Zone Capabilities */
    public const val cooking_zone_capabilities: Int = 0x2C29

    /** Cooking Zone Desired Cooking Conditions */
    public const val cooking_zone_desired_cooking_conditions: Int = 0x2C2A

    /** Cooking Zone Actual Cooking Conditions */
    public const val cooking_zone_actual_cooking_conditions: Int = 0x2C2B

    /** Cookware Sensor Data */
    public const val cookware_sensor_data: Int = 0x2C2C

    /** Cookware Sensor Aggregate */
    public const val cookware_sensor_aggregate: Int = 0x2C2D

    /** Cooking Temperature */
    public const val cooking_temperature: Int = 0x2C2E

    /** Cooking Zone Perceived Power */
    public const val cooking_zone_preceived_power: Int = 0x2C2F

    /** Kitchen Appliance Airflow */
    public const val kitchen_appliance_airflow: Int = 0x2C30

    /** Voice Assistant Name */
    public const val voice_assistant_name: Int = 0x2C31

    /** Voice Assistant UUID */
    public const val voice_assistant_uuid: Int = 0x2C32

    /** Voice Assistant Service Control Point */
    public const val voice_assistant_service_control_point: Int = 0x2C33

    /** Installed Location */
    public const val installed_location: Int = 0x2C34

    /** Voice Assistant Session State */
    public const val voice_assistant_session_state: Int = 0x2C35

    /** Voice Assistant Session Flag */
    public const val voice_assistant_session_flag: Int = 0x2C36

    /** Voice Assistant Supported Languages */
    public const val voice_assistant_supported_languages: Int = 0x2C37

    /** Voice Assistant Supported Features */
    public const val voice_assistant_supported_features: Int = 0x2C38

    /** HID SCI Mode */
    public const val hid_sci_mode: Int = 0x2C39

    /** HID SCI Information */
    public const val hid_sci_information: Int = 0x2C3A
}

/**
 * Bluetooth SIG assigned numbers for descriptors.
 *
 * Constant names exactly match the IDs defined in the Bluetooth SIG assigned numbers YAML file
 * (e.g. `org.bluetooth.descriptor.gatt.client_characteristic_configuration`).
 *
 * https://bitbucket.org/bluetooth-SIG/public/src/main/assigned_numbers/uuids/descriptors.yaml
 */
public object descriptor {
    public object gatt {
        /** Characteristic Extended Properties */
        public const val characteristic_extended_properties: Int = 0x2900

        /** Characteristic User Description */
        public const val characteristic_user_description: Int = 0x2901

        /** Client Characteristic Configuration */
        public const val client_characteristic_configuration: Int = 0x2902

        /** Server Characteristic Configuration */
        public const val server_characteristic_configuration: Int = 0x2903

        /** Characteristic Presentation Format */
        public const val characteristic_presentation_format: Int = 0x2904

        /** Characteristic Aggregate Format */
        public const val characteristic_aggregate_format: Int = 0x2905
    }

    /** Valid Range */
    public const val valid_range: Int = 0x2906

    /** External Report Reference */
    public const val external_report_reference: Int = 0x2907

    /** Report Reference */
    public const val report_reference: Int = 0x2908

    /** Number of Digitals */
    public const val number_of_digitals: Int = 0x2909

    /** Value Trigger Setting */
    public const val value_trigger_setting: Int = 0x290A

    /** Environmental Sensing Configuration */
    public const val es_configuration: Int = 0x290B

    /** Environmental Sensing Measurement */
    public const val es_measurement: Int = 0x290C

    /** Environmental Sensing Trigger Setting */
    public const val es_trigger_setting: Int = 0x290D

    /** Time Trigger Setting */
    public const val time_trigger_setting: Int = 0x290E

    /** Complete BR-EDR Transport Block Data */
    public const val complete_br_edr_transport_block_data: Int = 0x290F

    /** Observation Schedule */
    public const val observation_schedule: Int = 0x2910

    /** Valid Range and Accuracy */
    public const val valid_range_accuracy: Int = 0x2911

    /** Measurement Description */
    public const val measurement_description: Int = 0x2912

    /** Manufacturer Limits */
    public const val manufacturer_limits: Int = 0x2913

    /** Process Tolerances */
    public const val process_tolerances: Int = 0x2914

    /** IMD Trigger Setting */
    public const val imd_trigger_setting: Int = 0x2915

    /** Cooking Sensor Info */
    public const val cooking_sensor_info: Int = 0x2916

    /** Cooking Trigger Setting */
    public const val cooking_trigger_setting: Int = 0x2917
}
