# Build Linux dynamic libraries against CentOS 7's glibc 2.17 (rather than the glibc of the default
# `cross` images) for compatibility with older Linux distributions (e.g. Raspberry Pi OS).
# https://github.com/JuulLabs/kable/issues/990

[target.x86_64-unknown-linux-gnu]
image = "ghcr.io/cross-rs/x86_64-unknown-linux-gnu:main-centos"

[target.aarch64-unknown-linux-gnu]
image = "ghcr.io/cross-rs/aarch64-unknown-linux-gnu:main-centos"
