name: CI
on:
  pull_request:
  push:
    branches:
      # Trigger on merges to `main` to allow `gradle/actions/setup-gradle` to write its caches.
      # https://github.com/gradle/actions/blob/main/docs/setup-gradle.md#using-the-cache-read-only
      - main

jobs:
  assemble-rust:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - runner: macos-15-intel
          - runner: windows-latest

          # Linux dynamic libraries are built with `cross` (in Docker containers) to link against
          # an older glibc than provided by the GitHub runners, for compatibility with older Linux
          # distributions (e.g. Raspberry Pi OS).
          # https://github.com/JuulLabs/kable/issues/990
          - runner: ubuntu-latest
            cargo: cross
            target: x86_64-unknown-linux-gnu
          - runner: ubuntu-latest
            cargo: cross
            target: aarch64-unknown-linux-gnu
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-java@v5
        with:
          java-version-file: .sdkmanrc
      - uses: gradle/actions/setup-gradle@v6
      - if: matrix.cargo == 'cross'
        run: cargo install cross --git https://github.com/cross-rs/cross
      - run: ./gradlew :kable-core:compileKotlinJvm
        env:
          UNIFFI_CARGO: ${{ matrix.cargo }}
          UNIFFI_TARGET: ${{ matrix.target }}
      - run: unzip kable-btleplug-ffi.jar && rm -rf META-INF com *.jar
        working-directory: kable-btleplug-ffi/build/libs
        shell: bash
      - uses: actions/upload-artifact@v7
        with:
          name: kable-btleplug-ffi-${{ matrix.target || matrix.runner }}
          path: kable-btleplug-ffi/build/libs/
          if-no-files-found: error
          retention-days: 1

  build:
    runs-on: macos-latest
    needs: assemble-rust
    steps:
      - uses: actions/checkout@v7
      - uses: actions/download-artifact@v8
        with:
          path: kable-btleplug-ffi/build/external
          pattern: kable-btleplug-ffi-*
          merge-multiple: true
      - uses: actions/setup-java@v5
        with:
          java-version-file: .sdkmanrc
      - uses: gradle/actions/setup-gradle@v6

      - run: ./gradlew assemble -PsuppressWarnings=true
      - run: ./gradlew check
      - run: ./gradlew -PRELEASE_SIGNING_ENABLED=false publishToMavenLocal
