name: GitHub Pages
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 17
      - uses: gradle/actions/setup-gradle@v6
        with:
          cache-read-only: true

      - run: ./gradlew dokkaGenerate
      - run: >
          tar
          --verbose
          --dereference --hard-dereference
          --directory build/dokkaHtmlMultiModule
          --create --file '${{ runner.temp }}/artifact.tar'
          --exclude=.git
          --exclude=.github
          .

      - run: ./gradlew :shared:wasmJsBrowserDistribution
        working-directory: samples/sensortag

      - run: >
          tar
          --verbose
          --dereference --hard-dereference
          --directory shared/build/dist/wasmJs/productionExecutable
          --transform 's|^|sensortag/|'
          --append --file '${{ runner.temp }}/artifact.tar'
          --exclude=.git
          --exclude=.github
          .
        working-directory: samples/sensortag

      - uses: actions/upload-artifact@v7
        with:
          name: github-pages
          path: ${{ runner.temp }}/artifact.tar
          retention-days: 1
          if-no-files-found: error

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/deploy-pages@v5
        id: deployment
