name: Release Drafter
# https://github.com/release-drafter/release-drafter#usage

on:
  push:
    branches:
      - main

jobs:
  update-release-draft:
    permissions:
      contents: write
      pull-requests: read
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
